
// ********RoostGPT********
/*
Test generated by RoostGPT for test flight-reservation-unit using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test flight-reservation-unit using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test flight-reservation-unit using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=addFlight_eb6c4bc353
ROOST_METHOD_SIG_HASH=addFlight_e245295bc6

"""
  Scenario 1: Testing the successful addition of a new flight

  Details:
    TestName: addValidFlight.
    Description: This test will ensure that a new flight can be successfully added to the repository. This will test the default behavior of the method.
  Execution:
    Arrange: Create and initialize a new instance of Flight. Mock flightRepository to expect the save method with the new flight as a parameter.
    Act: Invoke the addFlight method with the aforementioned flight and an empty ModelMap as parameters.
    Assert: Verify that the save method was invoked in the mock flightRepository. Check whether the returned view string matches "flights/addFlight", and the model map contains the entry ("msg", "Flight Added Successfully").
  Validation:
    Assert these outcomes to ensure that the flight was saved in the repository, the correct message was added to the model map, and the correct view was returned. This maintains data consistency and verifies the functionality of the addFlight method.


  Scenario 2: Testing the addition of a null flight

  Details:
    TestName: addNullFlight.
    Description: This test will validate how the method handles the condition when a null flight is added. This scenario tests the method's null input handling.
  Execution:
    Arrange: Mock flightRepository's save method to throw IllegalArgumentException when null is passed as argument.
    Act: Invoke the addFlight method with null and an empty ModelMap as parameters.
    Assert: Verify that an IllegalArgumentException was thrown by the save method. The model map should not have any new entries, and the returned view should still be "flights/addFlight".
  Validation:
    NULL input should be considered invalid, and the system should respond accordingly, without adding any new entries or altering data.

"""
*/

// ********RoostGPT********

package com.flightreservation.flightreservation.controllers;

import com.flightreservation.flightreservation.domains.Flight;
import com.flightreservation.flightreservation.repositories.FlightRepository;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.ModelMap;
import java.util.HashMap;
import java.util.Map;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.verify;
import static org.mockito.MockitoAnnotations.initMocks;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import java.util.Date;
import java.util.List;

public class FlightControllerAddFlightTest {

	@InjectMocks
	FlightController flightController;

	@Mock
	FlightRepository flightRepository;

	@Before
	public void setUp() throws Exception {
		initMocks(this);
	}

	@Test
	@Category(Categories.valid.class)
	public void addValidFlight() {
		Flight flight = new Flight();
		ModelMap modelMap = new ModelMap();
		String resultView = flightController.addFlight(flight, modelMap);
		verify(flightRepository).save(flight);
		assertEquals("flights/addFlight", resultView);
		Map<String, Object> model = new HashMap<>();
		model.put("msg", "Flight Added Successfully");
		assertTrue(modelMap.containsAttribute("msg"));
		assertEquals(model, modelMap);
	}

	@Test(expected = IllegalArgumentException.class)
	@Category(Categories.invalid.class)
	public void addNullFlight() {
		ModelMap modelMap = new ModelMap();
		doThrow(IllegalArgumentException.class).when(flightRepository).save(null);
		String resultView = flightController.addFlight(null, modelMap);

		verify(flightRepository).save(null);
		assertEquals("flights/addFlight", resultView);
		assertTrue(!modelMap.containsAttribute("msg"));
	}

}