
// ********RoostGPT********
/*
Test generated by RoostGPT for test flight-reservation-unit using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test flight-reservation-unit using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=addFlight_eb6c4bc353
ROOST_METHOD_SIG_HASH=addFlight_e245295bc6

"""
Scenario 1: Normal scenario where the flight is added successfully.

Details:
  TestName: normalAddFlightScenario
  Description: This test is meant to check if the flight is being saved into the repository properly and if the message returned is correct.
Execution:
  Arrange: Create a Flight object with the needed details and a mock FlightRepository with its save method set to store the flight.
  Act: Invoke addFlight method with the created Flight object and ModelMap.
  Assert: Check if the "msg" attribute of the ModelMap has the value "Flight Added Successfully".
Validation:
  If the above assertion is true, that means the flight details have been saved into the repository and the right message is being returned in ModelMap. This is a critical operation to ensure that new flights can be added to the system.

Scenario 2: Scenario where the flight trying to be added is already there in the system.

Details:
  TestName: duplicateAddFlightScenario
  Description: This test is to check for the scenario where the flight being added is already present in the repository.
Execution:
  Arrange: Create a Flight object with the needed details and a mock FlightRepository with its save method configured to throw a DataIntegrityViolationException.
  Act: Invoke addFlight method with the created Flight object and ModelMap.
  Assert: Check if an exception was thrown.
Validation:
  If an exception was thrown that would mean the system is handling duplicate flights properly.

Scenario 3: Scenario where the flight information provided is incomplete or incorrect.

Details:
  TestName: invalidAddFlightScenario
  Description: This test is meant to check if the system handles wrongly formed or incomplete Flight objects properly.
Execution:
  Arrange: Create a Flight object with incomplete or incorrect details and a mock FlightRepository.
  Act: Invoke addFlight method with the created Flight object and ModelMap.
  Assert: Check if an exception was thrown.
Validation:
  If an exception was thrown, that would mean that the system doesn't accept Flight objects with insufficient or incorrect details which is the correct behavior as every detail is important for flight details.

  """
*/

// ********RoostGPT********
package com.flightreservation.flightreservation.controllers;

import com.flightreservation.flightreservation.domains.Flight;
import com.flightreservation.flightreservation.repositories.FlightRepository;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;
import org.springframework.ui.ModelMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import java.util.Date;
import java.util.List;

public class FlightControllerAddFlightTest {

	@Mock
	FlightRepository mockFlightRepository;

	@InjectMocks
	FlightController flightController;

	@Test
	@Category(Categories.valid.class)
	public void normalAddFlightScenario() {
		Flight flight = new Flight();
		ModelMap modelMap = new ModelMap();
		when(mockFlightRepository.save(any(Flight.class))).thenReturn(null);
		String result = flightController.addFlight(flight, modelMap);
		assertEquals("flights/addFlight", result);
		assertEquals("Flight Added Successfully", modelMap.get("msg"));
	}

	@Test(expected = RuntimeException.class)
	@Category(Categories.invalid.class)
	public void duplicateAddFlightScenario() {
		Flight flight = new Flight();
		ModelMap modelMap = new ModelMap();
		when(mockFlightRepository.save(any(Flight.class))).thenThrow(RuntimeException.class);
		flightController.addFlight(flight, modelMap);
	}

	@Test(expected = RuntimeException.class)
	@Category(Categories.invalid.class)
	public void invalidAddFlightScenario() {
		Flight flight = new Flight();
		ModelMap modelMap = new ModelMap();
		flightController.addFlight(flight, modelMap);
	}

}